name: Dry run upload public
on: push

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "dry-run"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
# Dry run
  dry-run-deploy:
    name: Deploy site - dry run
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v4
      with:
        path: ./public
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.netim.hosting
        username: ZR33031_FTP1
        password: ${{ secrets.FTP_PASSWORD }}
        dry-run: true
        local-dir: ./public/
        server-dir: /public_www/
        protocol: ftp
        timeout: 30000
